### PR TITLE
Rewrite

### PR DESCRIPTION
**Pull request by paul-court**
I have been through the entire class and removed anything that is now removed in Mongo 2.2 (connect and persist options to the Mongo() class).

I have also made some options that effect performance configurable.

Finally, I have re-written _lock to only use 1 query. 

So far this seems to be having a positive effect on our performance - but this is on the edge of my Mongo and PHP Session knowledge, so these changes are deffo in need of peer review / testing.

(Oh, and I have added a unit test.)

### CODE REVIEW

**Comment by cballou** [comment]
Much thanks for the pull requests :) I'll need to do a bit of testing before I merge. I'm thinking I'll also create a new branch naming structure to match the lowest MongoDB version (2.2 in this case) and update the README accordingly to indicate this. 

 I'll also update the docs and docblock to give you credit since you've put in so much work on this. Lastly, I'm probably going to drop in an MIT license and Composer/Packagist support for the masses.

Corey

**Comment by holtkamp** [comment]
he cballou, nice work you did here, further improved by gargoyle. 

I was looking for the composer.json file and noticed this issue. Any idea of when this can be expected?

Cheers

**Comment by cballou** [comment]
Argh, I've been swamped. Sorry this has been forgotten :-/ I just went ahead and added @gargoyle as a collaborator on the project. You're now free to update the core repository with your changes, but I'd still suggest the proposed changes above (README update, new branch).

**Comment by paul-court** [comment]
Do you need me to re-do this PR into another branch, or are you going to branch the current master -> legacy and keep that, and then have the new stuff continuing to develop in master?

**Comment by cballou** [comment]
I'm likely to break out and create a new major release version 
specifically for gargoyle's changes. I'll implement this into that one, 
2.0.0.

On 03/01/2013 07:59 AM, Paul wrote:

> Do you need me to re-do this PR into another branch, or are you going 
> to branch the current master -> legacy and keep that, and then have 
> the new stuff continuing to develop in master?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/cballou/MongoSession/pull/4#issuecomment-14288083.

## 

Corey Ballou
Web Developer
(315) 751-0002
http://coreyballou.com

**Pull request closed without merging**
